import Foundation

/// 把 PixShell 暴露成 **MCP server**，让支持 MCP 的工具（Claude Code CLI / Claude Desktop / Cursor …）
/// 直接把这个 SSH 客户端当工具用：读终端画面、往终端敲字、执行命令、翻远端目录。
///
/// 为什么走 MCP：桌面 AI 应用和 CLI agent 的**共同**标准接口就是它。做一次注册，所有支持 MCP 的
/// 客户端通吃 —— 这才叫"无缝联动"，而不是每个工具单独适配一遍。
///
/// 实现取巧：MCP over stdio 本质就是**行分隔的 JSON-RPC**，不需要任何 SDK。
/// 这个 python 脚本只做协议壳子，真正干活转手给已经生成好的 `pixshell` 命令
/// （见 AgentCLI），所以两条路径共用同一套桥调用，行为不会漂。
enum AgentMCP {

    static var scriptPath: URL { AgentCLI.binDir.appendingPathComponent("pixshell-mcp") }

    static func install() {
        do {
            try FileManager.default.createDirectory(at: AgentCLI.binDir, withIntermediateDirectories: true)
            let body = script()
            let existing = try? String(contentsOf: scriptPath, encoding: .utf8)
            if existing != body { try body.write(to: scriptPath, atomically: true, encoding: .utf8) }
            try FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: scriptPath.path)
            Log.info("MCP server 就绪：\(scriptPath.path)", "bridge")
        } catch {
            Log.warn("写 MCP server 失败：\(error.localizedDescription)", "bridge")
        }
    }

    /// Claude Code CLI 的一行注册命令。
    static func claudeCodeCommand() -> String {
        "claude mcp add pixshell -- \(shellQuotedPath(scriptPath.path))"
    }

    /// Claude Desktop 等「配置文件型」客户端的 JSON 片段。
    static func desktopConfigSnippet() -> String {
        let command = jsonQuotedPath(scriptPath.path)
        return """
        {
          "mcpServers": {
            "pixshell": {
              "command": \(command)
            }
          }
        }
        """
    }

    private static func shellQuotedPath(_ path: String) -> String {
        "\"" + path.replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"") + "\""
    }

    private static func jsonQuotedPath(_ path: String) -> String {
        "\"" + path.replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"") + "\""
    }

    private static func script() -> String {
        let appPath = Bundle.main.bundlePath
        let instructions = pythonQuoted(AgentCLI.mcpInstructions())
        let lines: [String] = [
            "#!/usr/bin/env python3",
            "# PixShell MCP server —— 由 App 自动生成，勿手改（下次启动会被覆盖）。",
            "# stdio 上的行分隔 JSON-RPC；**直接 HTTP 调本地桥**（不经过 bash wrapper），",
            "# 每个工具调用 = 1 线程 + 1 HTTP 请求，无子进程，支持高并发。",
            "import json, os, subprocess, sys, time, socket, urllib.request, urllib.error, threading, re, uuid",
            "os.umask(0o077)",
            "",
            "# 日志：MCP server 跑在客户端的子进程里，stderr 通常被吞掉 —— 不写文件就完全没法查。",
            "LOG = os.path.expanduser('~/Library/Application Support/PixShell/logs/agent-mcp.log')",
            "def log(msg):",
            "    try:",
            "        os.makedirs(os.path.dirname(LOG), exist_ok=True)",
            "        if os.path.exists(LOG) and os.path.getsize(LOG) > 2_000_000:",
            "            with open(LOG, 'rb') as f: f.seek(-1_000_000, 2); tail = f.read()",
            "            with open(LOG, 'wb') as f: f.write(tail)",
            "        with open(LOG, 'a', encoding='utf-8') as f:",
            "            f.write('%s [mcp] %s\\n' % (time.strftime('%Y-%m-%dT%H:%M:%S'), msg))",
            "        os.chmod(LOG, 0o600)",
            "    except Exception:",
            "        pass",
            "",
            "# 直连桥：端口（可被 PIXSHELL_BRIDGE_PORT 覆盖）+ token 文件 + App 路径（自动拉起用）。",
            "# 默认读 agent_port 文件（端口池避让后的实际端口），文件缺失才回落主端口 47866。",
            "PORT = os.environ.get('PIXSHELL_BRIDGE_PORT', '')",
            "if not PORT:",
            "    try:",
            "        with open(os.path.expanduser('~/Library/Application Support/PixShell/agent_port'), 'r', encoding='utf-8') as f:",
            "            PORT = f.read().strip()",
            "    except Exception:",
            "        pass",
            "if not PORT or not PORT.isdigit():",
            "    PORT = '47866'",
            "BASE = 'http://127.0.0.1:%s/v1/app' % PORT",
            "TOKEN_FILE = os.path.expanduser('~/Library/Application Support/PixShell/agent_token')",
            "APP_PATH = " + jsonQuoted(appPath),
            "",
            "# MCP 客户端对单条工具结果的大小很敏感：一次回几 MB 基本必炸（撑爆上下文/超帧长）。",
            "# 所以这里**统一在协议层截断**，并且明确告诉调用方截了多少、怎么拿更多 —— 绝不闷声截断。",
            "DEFAULT_MAX = 60000",
            "HARD_MAX = 200000",
            "ARTIFACT_DIR = os.path.expanduser('~/Library/Application Support/PixShell/artifacts')",
            "ARTIFACT_MAX = 512 * 1024 * 1024",
            "",
            "def _safe_artifact_name(name):",
            "    name = os.path.basename(str(name or '').replace('\\\\', '/')).strip()",
            "    if not name or name in ('.', '..'):",
            "        name = 'artifact'",
            "    name = re.sub(r'[^A-Za-z0-9._-]+', '_', name)",
            "    return name[:120]",
            "",
            "def _artifact_path(name):",
            "    return os.path.join(ARTIFACT_DIR, _safe_artifact_name(name))",
            "",
            "def write_artifact(name, text):",
            "    os.makedirs(ARTIFACT_DIR, exist_ok=True)",
            "    path = _artifact_path(name)",
            "    with open(path, 'w', encoding='utf-8', errors='replace') as f:",
            "        f.write(text or '')",
            "    size = os.path.getsize(path)",
            "    if size > ARTIFACT_MAX:",
            "        with open(path, 'r', encoding='utf-8', errors='replace') as f:",
            "            f.seek(max(0, size - ARTIFACT_MAX))",
            "            tail = f.read()",
            "        with open(path, 'w', encoding='utf-8', errors='replace') as f:",
            "            f.write(tail)",
            "    return {'path': path, 'bytes': os.path.getsize(path)}",
            "",
            "def read_artifact(name, max_bytes=DEFAULT_MAX, offset=0):",
            "    path = _artifact_path(name)",
            "    if not os.path.isfile(path):",
            "        return (f'artifact not found: {name} -> {path}', True)",
            "    size = os.path.getsize(path)",
            "    max_bytes = max(1000, min(int(max_bytes or DEFAULT_MAX), 1024 * 1024))",
            "    offset = max(0, int(offset or 0))",
            "    with open(path, 'r', encoding='utf-8', errors='replace') as f:",
            "        if offset:",
            "            f.seek(offset)",
            "        text = f.read(max_bytes)",
            "    return (f'[artifact] path={path} size={size} offset={offset} bytes={len(text.encode(\"utf-8\", \"replace\"))}\\n' + text, False)",
            "",
            "def clamp(text, max_bytes=DEFAULT_MAX):",
            "    max_bytes = max(1000, min(int(max_bytes or DEFAULT_MAX), HARD_MAX))",
            "    b = text.encode('utf-8', 'replace')",
            "    if len(b) <= max_bytes:",
            "        return text",
            "    # 头尾都留：报错信息经常在末尾，只留头部会把关键行切没",
            "    head = b[: int(max_bytes * 0.6)].decode('utf-8', 'ignore')",
            "    tail = b[-int(max_bytes * 0.35):].decode('utf-8', 'ignore')",
            "    dropped = len(b) - len(head.encode()) - len(tail.encode())",
            "    return (head + '\\n\\n…… [PixShell 截断：略去约 %d 字节，共 %d 字节] ……\\n' % (dropped, len(b))",
            "            + '提示：用 grep/head/tail/sed -n 收窄，或调大 max_bytes（上限 %d）。\\n\\n' % HARD_MAX + tail)",
            "",
            "MCP_INSTRUCTIONS = \(instructions)",
            "",
            "TOOLS = [",
            "    {\"name\": \"list_sessions\", \"description\": \"先调用此工具获取当前 SSH session 编号和 connected 状态；不要猜 session，也不要缓存跨 App 重启的编号。返回 session/title/host/host_id/username/connected/active，不含密码或私钥。\",",
            "     \"inputSchema\": {\"type\": \"object\", \"properties\": {}}},",
            "    {\"name\": \"read_screen\", \"description\": \"读取交互 PTY 最近画面；判断终端状态、确认提示符或执行 type_text 后必须优先调用。断线恢复时可能返回一次性上下文重置提示；无效或普通死 session 通常返回 404。\",",
            "     \"inputSchema\": {\"type\": \"object\", \"properties\": {",
            "        \"lines\": {\"type\": \"integer\", \"default\": 200, \"minimum\": 1, \"maximum\": 2000, \"description\": \"读取行数，默认 200，最大 2000\"},",
            "        \"session\": {\"type\": \"integer\", \"default\": 0, \"minimum\": 0, \"description\": \"session 编号；先使用 list_sessions 确认\"}}}},",
            "    {\"name\": \"exec_command\", \"description\": \"通过已认证会话执行一次性命令并返回输出；绝不重新建立连接或重新认证（防封禁铁律）。不会把命令输入交互画面。只读查询优先用它；大输出请用 grep/head/tail 或 write_artifact。死 session 会尝试原地重连，越界通常返回 410。\",",
            "     \"inputSchema\": {\"type\": \"object\", \"properties\": {",
            "        \"command\": {\"type\": \"string\", \"description\": \"要执行的远端命令，必填；不要直接 cat 大文件\"},",
            "        \"session\": {\"type\": \"integer\", \"default\": 0, \"minimum\": 0, \"description\": \"session 编号；先使用 list_sessions 确认\"},",
            "        \"max_bytes\": {\"type\": \"integer\", \"default\": 60000, \"minimum\": 1000, \"maximum\": 200000, \"description\": \"返回 stdout 上限，默认 60000，最大 200000；超限会保留头尾并提示截断\"},",
            "        \"timeout\": {\"type\": \"integer\", \"minimum\": 1000, \"description\": \"命令超时，单位毫秒；默认约 30000，长任务可传 300000 等更大值\"},",
            "        \"write_artifact\": {\"type\": \"boolean\", \"default\": False, \"description\": \"为 true 时把完整 stdout 写入本机 artifact，返回引用而不是大段文本\"},",
            "        \"artifact_name\": {\"type\": \"string\", \"description\": \"artifact 文件名，可选；随后用 read_artifact 的 basename 读取\"}},",
            "        \"required\": [\"command\"]}},",
            "    {\"name\": \"read_artifact\", \"description\": \"分块读取 exec_command(write_artifact=true) 生成的本机 artifact。用 offset 继续读取，不要一次性把大文件塞进上下文。\",",
            "     \"inputSchema\": {\"type\": \"object\", \"properties\": {",
            "        \"name\": {\"type\": \"string\", \"description\": \"artifact basename，必填\"},",
            "        \"offset\": {\"type\": \"integer\", \"default\": 0, \"minimum\": 0, \"description\": \"字节偏移，默认 0\"},",
            "        \"max_bytes\": {\"type\": \"integer\", \"default\": 60000, \"minimum\": 1000, \"maximum\": 1048576, \"description\": \"本次读取字节数，默认 60000，最大 1MB\"}},",
            "        \"required\": [\"name\"]}},",
            "    {\"name\": \"type_text\", \"description\": \"向交互 PTY 写入文本，自动追加换行并返回约 40 行画面；用于 vim/top/交互确认。不是 exec_command 的替代品，调用后应再 read_screen。断线恢复后的第一次调用可能只触发重连而不发送本次输入。\",",
            "     \"inputSchema\": {\"type\": \"object\", \"properties\": {",
            "        \"text\": {\"type\": \"string\", \"description\": \"要输入到交互 PTY 的文本，必填；可能被自动追加换行\"},",
            "        \"session\": {\"type\": \"integer\", \"default\": 0, \"minimum\": 0, \"description\": \"session 编号；先使用 list_sessions 确认\"}},",
            "        \"required\": [\"text\"]}},",
            "    {\"name\": \"list_hosts\", \"description\": \"列出 PixShell 已保存主机的 ID、名称、地址、端口、用户和分组；不返回密码或私钥。用于 ssh/connect 前查找目标。connect/ssh 的 host 参数可直接传 主机ID、地址(IP/域名) 或 名称（三者都接受；多个名称包含匹配时需用精确 ID）。\",",
            "     \"inputSchema\": {\"type\": \"object\", \"properties\": {}}},",
            "    {\"name\": \"connect\", \"description\": \"连接已保存的 SSH 主机并返回 session 编号（供 exec_command/type_text/read_screen/sftp 系列使用）。host 可传 主机ID、地址(IP/域名) 或 名称；同一主机重复连接会复用现有会话并返回相同 session。当前没有任何会话时必须先调用本工具，不要对 session 0 反复尝试。\",",
            "     \"inputSchema\": {\"type\": \"object\", \"properties\": {",
            "        \"host\": {\"type\": \"string\", \"description\": \"主机ID、地址或名称；不确定时先 list_hosts 查\"}},",
            "        \"required\": [\"host\"]}},",
            "    {\"name\": \"sftp_list\", \"description\": \"通过独立 SFTP 连接列远端目录；不改变交互 shell 的 cwd，也不代表交互 shell 健康。\",",
            "     \"inputSchema\": {\"type\": \"object\", \"properties\": {",
            "        \"path\": {\"type\": \"string\", \"default\": \".\", \"description\": \"远端目录路径，默认 .\"},",
            "        \"session\": {\"type\": \"integer\", \"default\": 0, \"minimum\": 0, \"description\": \"session 编号；先使用 list_sessions 确认\"}}}},",
            "    {\"name\": \"sftp_upload\", \"description\": \"通过独立 SFTP 把本地文件上传到远端；local_path 是运行 AI 的本机路径，remote_path 是 SSH 主机路径。破坏性覆盖操作仍需用户确认。\",",
            "     \"inputSchema\": {\"type\": \"object\", \"properties\": {",
            "        \"local_path\": {\"type\": \"string\", \"description\": \"本机文件路径，必填\"}, \"remote_path\": {\"type\": \"string\", \"description\": \"远端目标路径，必填\"},",
            "        \"session\": {\"type\": \"integer\", \"default\": 0, \"minimum\": 0, \"description\": \"session 编号；先使用 list_sessions 确认\"}}, \"required\": [\"local_path\", \"remote_path\"]}},",
            "    {\"name\": \"sftp_download\", \"description\": \"通过独立 SFTP 把远端文件下载到本机；remote_path 是远端路径，local_path 是本机目标路径。成功返回本地路径。\",",
            "     \"inputSchema\": {\"type\": \"object\", \"properties\": {",
            "        \"remote_path\": {\"type\": \"string\", \"description\": \"远端文件路径，必填\"}, \"local_path\": {\"type\": \"string\", \"description\": \"本机目标路径，可选；省略时由桥生成临时路径\"},",
            "        \"session\": {\"type\": \"integer\", \"default\": 0, \"minimum\": 0, \"description\": \"session 编号；先使用 list_sessions 确认\"}}, \"required\": [\"remote_path\"]}},",
            "    {\"name\": \"bridge_status\", \"description\": \"检查本地 PixShell bridge 是否在线、实际端口和 artifact 目录。桥只绑定 127.0.0.1，token 由脚本管理；不要读取或打印 token。\",",
            "     \"inputSchema\": {\"type\": \"object\", \"properties\": {}}},",
            "]",
            "",
            "# 桥操作：直接 urllib 调本地桥（无 bash wrapper 子进程）。",
            "# 桥未就绪时自动拉起 App（无头）并等就绪，然后重试一次。",
            "# 返回 (响应 dict, is_error)。",
            "def token():",
            "    try:",
            "        with open(TOKEN_FILE, 'r', encoding='utf-8') as f:",
            "            return f.read().strip()",
            "    except Exception:",
            "        return ''",
            "",
            "def bridge_alive():",
            "    # HTTP /v1/health 探测（带短超时）：比裸 TCP 更准 —— 桥进程活着但主线程挂死时",
            "    # 端口仍 LISTEN，裸 TCP 会误判\"活着\"，导致永不拉起、每次调用干等 120s。",
            "    # 铁律：/v1/health 在鉴权守卫**后面**，不带 token 恒 401 → 恒返回 False →",
            "    # 每次调用异常都误判\"桥死\"，疯狂拉起新无头实例。必须带 Bearer token 探测。",
            "    try:",
            "        req = urllib.request.Request('http://127.0.0.1:%s/v1/health' % PORT)",
            "        req.add_header('Authorization', 'Bearer ' + token())",
            "        with urllib.request.urlopen(req, timeout=1.5) as r:",
            "            return r.status == 200",
            "    except urllib.error.HTTPError as he:",
            "        # 401=鉴权被拒但桥在响应（token 过期/错位等），仍算活着；只有连不上才算死。",
            "        return he.code == 401",
            "    except Exception:",
            "        return False",
            "",
            "# 全局拉起去重：并发调用同时探测到桥死时，只触发一次 open，避免竞态多拉。",
            "_LAUNCHING = {'lock': threading.Lock(), 'last': 0.0}",
            "def _launch_app():",
            "    with _LAUNCHING['lock']:",
            "        now = time.time()",
            "        if now - _LAUNCHING['last'] < 5:",
            "            return False  # 5s 冷却：上次刚拉过，别重复拉",
            "        _LAUNCHING['last'] = now",
            "    try:",
            "        # open -n 强制新实例：桥死后 GUI 还在跑时，普通 open 只会激活已有实例（no-op），",
            "        # --args 被丢弃 → 47866 永远空 → 通道永久死。必须 -n 强制起新的无头进程。",
            "        subprocess.Popen(['open', '-n', APP_PATH, '--args', '--headless'],",
            "                         stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)",
            "        return True",
            "    except Exception:",
            "        return False",
            "",
            "def _wait_bridge(sec):",
            "    for _ in range(sec * 2):",
            "        if bridge_alive(): return True",
            "        time.sleep(0.5)",
            "    return False",
            "",
            "def call(path, payload=None, query='', timeout=None):",
            "    url = BASE + '/' + path + (query or '')",
            "    data = json.dumps(payload).encode() if payload is not None else None",
            "    # 默认超时：exec 带显式 timeout 时用它（长任务），否则 45s（比客户端工具超时小，",
            "    # 失败更快暴露、信号量槽位更快回收；30s exec + 握手余量足够）。",
            "    to = timeout or 45",
            "    def do():",
            "        req = urllib.request.Request(url, data=data, method='POST' if data else 'GET')",
            "        req.add_header('Authorization', 'Bearer ' + token())",
            "        if data: req.add_header('Content-Type', 'application/json')",
            "        with urllib.request.urlopen(req, timeout=to) as r:",
            "            return json.loads(r.read().decode('utf-8', 'replace'))",
            "    try:",
            "        return do(), False",
            "    except urllib.error.HTTPError as he:",
            "        # 桥返回的业务错误（会话已断开 410 / 不存在 404 等）：提取 body 里的 error 信息透传，",
            "        # 别吞成模糊的 'HTTP Error 410' —— 那是 agent 分不清\"会话死了\"和\"桥坏了\"的根源。",
            "        try:",
            "            detail = json.loads(he.read().decode('utf-8', 'replace')).get('error', '')",
            "        except Exception:",
            "            detail = ''",
            "        return {'error': detail or ('桥返回 HTTP %d' % he.code)}, True",
            "    except Exception as e:",
            "        if not bridge_alive():",
            "            _launch_app()",
            "            if _wait_bridge(20):",
            "                try:",
            "                    return do(), False",
            "                except Exception as e2:",
            "                    return {'error': '调用 PixShell 桥失败: %s' % e2}, True",
            "        return {'error': '调用 PixShell 桥失败: %s' % e}, True",
            "",
            "def pick(d, *keys):",
            "    if not isinstance(d, dict): return json.dumps(d, ensure_ascii=False)",
            "    if 'error' in d and len(d) == 1: return str(d['error'])",
            "    for k in keys:",
            "        if k in d:",
            "            v = d[k]",
            "            return v if isinstance(v, str) else json.dumps(v, ensure_ascii=False)",
            "    return json.dumps(d, ensure_ascii=False)",
            "",
            "def call_tool(name, a):",
            "    log('tool %s keys=%s' % (name, ','.join(sorted(a.keys()))))",
            "    s = int(a.get('session') or 0)",
            "    if name == 'list_sessions':",
            "        d, e = call('sessions'); return (clamp(pick(d, 'sessions')), e)",
            "    if name == 'list_hosts':",
            "        d, e = call('hosts'); return (clamp(pick(d, 'hosts')), e)",
            "    if name == 'connect':",
            "        hkey = (a.get('host') or a.get('host_id') or '').strip()",
            "        if not hkey:",
            "            return ('缺少 host 参数（主机ID/地址/名称；先 list_hosts 查）', True)",
            "        d, e = call('connect', {'host_id': hkey}, timeout=45)",
            "        if e or (isinstance(d, dict) and not d.get('ok')):",
            "            return (clamp(pick(d, 'error', 'message')), True)",
            "        return (json.dumps({'session': d.get('session'), 'title': d.get('title')}, ensure_ascii=False), False)",
            "    if name == 'read_screen':",
            "        n = max(1, min(int(a.get('lines') or 200), 2000))   # 行数也钳住，别让 lines=999999 拖垮",
            "        d, e = call('screen', None, '?session=%d&lines=%d' % (s, n)); return (clamp(pick(d, 'text')), e)",
            "    if name == 'exec_command':",
            "        # 客户端可传 timeout（毫秒）——长任务（编译/脚本）不再被 30s 硬杀。",
            "        to_ms = a.get('timeout')",
            "        payload = {'session': s, 'cmd': a.get('command', '')}",
            "        if isinstance(to_ms, (int, float)) and to_ms > 0:",
            "            payload['timeout'] = int(to_ms)",
            "        # HTTP 超时 = 命令超时 + 握手/响应余量；上限 10 分钟防资源耗尽",
            "        cmd_to = int(to_ms / 1000.0) if isinstance(to_ms, (int, float)) and to_ms > 0 else 30",
            "        http_to = min(max(cmd_to + 15, 45), 600)",
            "        d, e = call('exec', payload, timeout=http_to)",
            "        # 显式超时/错误时把错误信息透传，别吞成模糊的失败",
            "        if e or (isinstance(d, dict) and d.get('error')):",
            "            return (clamp(pick(d, 'error', 'message')), True)",
            "        stdout = pick(d, 'output', 'text', 'stdout')",
            "        if a.get('write_artifact'):",
            "            try:",
            "                ref = write_artifact(a.get('artifact_name') or ('exec-%s.out' % uuid.uuid4().hex[:12]), stdout)",
            "                return (json.dumps({'artifact': ref['path'], 'bytes': ref['bytes'],",
            "                                    'hint': 'use read_artifact with name=<basename> to read chunks'}, ensure_ascii=False), False)",
            "            except Exception as e:",
            "                return ('write_artifact failed: %s' % e, True)",
            "        return (clamp(stdout, a.get('max_bytes')), False)",
            "    if name == 'type_text':",
            "        d, e = call('shell', {'session': s, 'text': a.get('text', '') + '\\n'})",
            "        if e: return (clamp(pick(d, 'error')), True)",
            "        time.sleep(0.6)",
            "        d2, e2 = call('screen', None, '?session=%d&lines=40' % s); return (clamp(pick(d2, 'text')), e2)",
            "    if name == 'sftp_list':",
            "        d, e = call('sftp/list', {'session': s, 'path': a.get('path', '.')}); return (clamp(pick(d, 'entries')), e)",
            "    if name == 'sftp_upload':",
            "        d, e = call('sftp/upload', {'session': s, 'local': a.get('local_path', ''), 'remote': a.get('remote_path', '')}, timeout=900)",
            "        if e: return (clamp(pick(d, 'error')), True)",
            "        return (clamp(pick(d, 'remotePath', 'path')), False)",
            "    if name == 'sftp_download':",
            "        d, e = call('sftp/download', {'session': s, 'remote': a.get('remote_path', ''), 'local': a.get('local_path', '')}, timeout=900)",
            "        if e: return (clamp(pick(d, 'error')), True)",
            "        return (clamp(pick(d, 'localPath', 'path')), False)",
            "    if name == 'read_artifact':",
            "        return read_artifact(a.get('name', ''), a.get('max_bytes'), a.get('offset'))",
            "    if name == 'bridge_status':",
            "        return (json.dumps({'port': PORT, 'alive': bridge_alive(), 'artifact_dir': ARTIFACT_DIR}, ensure_ascii=False), False)",
            "    return ('未知工具: %s' % name, True)",
            "",
            "# 并发工具调用：MCP 客户端（Claude Code 等）并行发多个 tools/call 时，",
            "# 若主循环同步逐行处理，一个慢 exec 会阻塞后续所有调用（实测：8s exec 让",
            "# 后续快命令等 9s+，正是\"一个调用后另一个排队超时\"的根因）。",
            "# 解法：tools/call 丢进线程并发执行，主循环只读 stdin 分发，谁先完成谁回；",
            "# 响应按 id 关联（MCP 规范允许乱序），stdout 写用锁保护防交错。",
            "# 直连 HTTP 后每工具调用 = 1 线程 + 1 HTTP 请求（无子进程），线程轻量，",
            "# 并发只受桥 + 系统资源限制；信号量仅作极端资源护栏（远超实际需求）。",
            "WRITE_LOCK = threading.Lock()",
            "# 高并发护栏：256 并发远超任何 MCP 客户端的并行工具调用数，防极端资源耗尽。",
            "MAX_CONCURRENT = 256",
            "CONCURRENT_SEM = threading.Semaphore(MAX_CONCURRENT)",
            "",
            "def reply(rid, result):",
            "    with WRITE_LOCK:",
            "        sys.stdout.write(json.dumps({'jsonrpc': '2.0', 'id': rid, 'result': result}) + '\\n')",
            "        sys.stdout.flush()",
            "",
            "def reply_error(rid, msg):",
            "    with WRITE_LOCK:",
            "        sys.stdout.write(json.dumps({'jsonrpc': '2.0', 'id': rid,",
            "            'error': {'code': -32601, 'message': msg}}) + '\\n')",
            "        sys.stdout.flush()",
            "",
            "def dispatch(msg):",
            "    # 铁律：任何异常都不得穿透主循环 —— 一次畸形请求杀死整个 MCP server 是",
            "    # \"通道老死\"的最隐蔽根因（客户端 bug / 脏帧随时可能来，尤其是批量 JSON-RPC 数组）。",
            "    try:",
            "        _dispatch(msg)",
            "    except Exception as e:",
            "        log('dispatch 异常: %r' % (e,))",
            "        try:",
            "            rid = msg.get('id') if isinstance(msg, dict) else None",
            "            reply_error(rid, 'server 内部异常: %s' % e)",
            "        except Exception:",
            "            pass",
            "",
            "def _dispatch(msg):",
            "    if not isinstance(msg, dict):",
            "        # JSON-RPC 批量数组 / null / 字符串：不是合法请求，回解析错误（不杀进程）",
            "        reply_error(None, 'invalid request: expected object')",
            "        return",
            "    method, rid = msg.get('method'), msg.get('id')",
            "    if method == 'initialize':",
            "        log('initialize 来自客户端')",
            "        reply(rid, {'protocolVersion': '2024-11-05', 'capabilities': {'tools': {}},",
            "                    'serverInfo': {'name': 'pixshell', 'version': '0.1.8'},",
            "                    'instructions': MCP_INSTRUCTIONS})",
            "    elif method == 'tools/list':",
            "        reply(rid, {'tools': TOOLS})",
            "    elif method == 'tools/call':",
            "        p = msg.get('params')",
            "        if not isinstance(p, dict):",
            "            reply_error(rid, 'invalid params: expected object')",
            "            return",
            "        args = p.get('arguments')",
            "        if not isinstance(args, dict): args = {}",
            "        # 并发执行：独立线程跑工具，主循环立即继续读 stdin。",
            "        # 护栏在创建线程**前** acquire —— 槽满直接回错，绝不无界建线程（防线程爆炸）。",
            "        if not CONCURRENT_SEM.acquire(timeout=0.5):",
            "            reply_error(rid, '并发槽已占满（>%d 个工具并行），请稍后重试' % MAX_CONCURRENT)",
            "            return",
            "        threading.Thread(target=handle_tool_call,",
            "                         args=(rid, p.get('name', ''), args),",
            "                         daemon=True).start()",
            "    elif method == 'ping':",
            "        reply(rid, {})",
            "    elif rid is not None:",
            "        # 未实现的方法要回错误，不能装死 —— 否则客户端会一直等",
            "        reply_error(rid, 'method not found: %s' % method)",
            "",
            "def handle_tool_call(rid, name, args):",
            "    # 信号量已在 dispatch 里 acquire（前置护栏），这里只负责执行 + 释放。",
            "    try:",
            "        text, is_err = call_tool(name, args)",
            "        reply(rid, {'content': [{'type': 'text', 'text': text}], 'isError': is_err})",
            "    except Exception as e:",
            "        log('tools/call 异常: %s' % e)",
            "        reply(rid, {'content': [{'type': 'text', 'text': '工具调用异常: %s' % e}], 'isError': True})",
            "    finally:",
            "        CONCURRENT_SEM.release()",
            "",
            "for raw in sys.stdin:",
            "    raw = raw.strip()",
            "    if not raw:",
            "        continue",
            "    try:",
            "        msg = json.loads(raw)",
            "    except Exception:",
            "        # 坏帧：尽量提取 id 回解析错误，别让客户端等超时杀进程",
            "        try:",
            "            rid = json.loads(raw).get('id') if raw.strip().startswith('{') else None",
            "            reply_error(rid, 'parse error')",
            "        except Exception:",
            "            pass",
            "        continue",
            "    dispatch(msg)",
            "",
        ]
        return lines.joined(separator: "\n")
    }

    /// Python 字符串字面量转义：指南包含换行、反引号和反斜杠，不能直接插入生成脚本。
    private static func pythonQuoted(_ s: String) -> String {
        let escaped = s
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "\r", with: "\\r")
            .replacingOccurrences(of: "\n", with: "\\n")
            .replacingOccurrences(of: "\t", with: "\\t")
        return "\"\(escaped)\""
    }

    /// 路径里可能有空格（Application Support），嵌进 python 前要加引号转义。
    /// **不要用 JSONSerialization**：它会把 `/` 转义成 `\/`，而 python 不认这个转义，
    /// 结果字符串里真的多出反斜杠，路径直接失效（实测踩过：No such file or directory '\/Users\/...'）。
    /// python 字符串只需要处理反斜杠和引号两样。
    private static func jsonQuoted(_ s: String) -> String {
        let escaped = s
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
        return "\"\(escaped)\""
    }
}
