/** Terminal color schemes (ANSI 16 + bg/fg/cursor/selection) for xterm theme.
 * native-112: curated working set only — removed bulk/obscure/low-contrast schemes
 * that looked identical or failed to show a visible change in the terminal.
 */
const SCHEMES = {
  "pix-dark": {
    "name": "Pix Dark (Default)",
    "background": "#002945",
    "foreground": "#ffffff",
    "cursor": "#00d05c",
    "selectionBackground": "#05609f",
    "black": "#555555",
    "red": "#ff2222",
    "green": "#38de21",
    "yellow": "#ffe50a",
    "blue": "#1460d2",
    "magenta": "#ff005d",
    "cyan": "#00bbbb",
    "white": "#bbbbbb",
    "brightBlack": "#555555",
    "brightRed": "#f40e17",
    "brightGreen": "#3bd01d",
    "brightYellow": "#edc809",
    "brightBlue": "#5555ff",
    "brightMagenta": "#ff99ff",
    "brightCyan": "#6ae3fa",
    "brightWhite": "#ffffff"
  },
  "dracula": {
    "name": "Dracula",
    "background": "#1e1f29",
    "foreground": "#f8f8f2",
    "cursor": "#bbbbbb",
    "selectionBackground": "#44475a",
    "black": "#000000",
    "red": "#ff5555",
    "green": "#50fa7b",
    "yellow": "#f1fa8c",
    "blue": "#bd93f9",
    "magenta": "#ff79c6",
    "cyan": "#8be9fd",
    "white": "#bbbbbb",
    "brightBlack": "#555555",
    "brightRed": "#ff5555",
    "brightGreen": "#50fa7b",
    "brightYellow": "#f1fa8c",
    "brightBlue": "#bd93f9",
    "brightMagenta": "#ff79c6",
    "brightCyan": "#8be9fd",
    "brightWhite": "#ffffff"
  },
  "monokai_soda": {
    "name": "Monokai Soda",
    "background": "#1a1a1a",
    "foreground": "#c4c5b5",
    "cursor": "#f6f7ec",
    "selectionBackground": "#343434",
    "black": "#1a1a1a",
    "red": "#f4005f",
    "green": "#98e024",
    "yellow": "#fa8419",
    "blue": "#9d65ff",
    "magenta": "#f4005f",
    "cyan": "#58d1eb",
    "white": "#c4c5b5",
    "brightBlack": "#625e4c",
    "brightRed": "#f4005f",
    "brightGreen": "#98e024",
    "brightYellow": "#e0d561",
    "brightBlue": "#9d65ff",
    "brightMagenta": "#f4005f",
    "brightCyan": "#58d1eb",
    "brightWhite": "#f6f6ef"
  },
  "gruvbox_dark": {
    "name": "Gruvbox Dark",
    "background": "#1e1e1e",
    "foreground": "#e6d4a3",
    "cursor": "#bbbbbb",
    "selectionBackground": "#685c51",
    "black": "#161819",
    "red": "#f73028",
    "green": "#aab01e",
    "yellow": "#f7b125",
    "blue": "#719586",
    "magenta": "#c77089",
    "cyan": "#7db669",
    "white": "#faefbb",
    "brightBlack": "#7f7061",
    "brightRed": "#be0f17",
    "brightGreen": "#868715",
    "brightYellow": "#cc881a",
    "brightBlue": "#377375",
    "brightMagenta": "#a04b73",
    "brightCyan": "#578e57",
    "brightWhite": "#e6d4a3"
  },
  "solarized_dark": {
    "name": "Solarized Dark",
    "background": "#001e27",
    "foreground": "#708284",
    "cursor": "#708284",
    "selectionBackground": "#002831",
    "black": "#002831",
    "red": "#d11c24",
    "green": "#738a05",
    "yellow": "#a57706",
    "blue": "#2176c7",
    "magenta": "#c61c6f",
    "cyan": "#259286",
    "white": "#eae3cb",
    "brightBlack": "#001e27",
    "brightRed": "#bd3613",
    "brightGreen": "#475b62",
    "brightYellow": "#536870",
    "brightBlue": "#708284",
    "brightMagenta": "#5956ba",
    "brightCyan": "#819090",
    "brightWhite": "#fcf4dc"
  },
  "solarized_dark_higher_contrast": {
    "name": "Solarized Dark Higher Contrast",
    "background": "#001e27",
    "foreground": "#9cc2c3",
    "cursor": "#f34b00",
    "selectionBackground": "#003748",
    "black": "#002831",
    "red": "#d11c24",
    "green": "#6cbe6c",
    "yellow": "#a57706",
    "blue": "#2176c7",
    "magenta": "#c61c6f",
    "cyan": "#259286",
    "white": "#eae3cb",
    "brightBlack": "#006488",
    "brightRed": "#f5163b",
    "brightGreen": "#51ef84",
    "brightYellow": "#b27e28",
    "brightBlue": "#178ec8",
    "brightMagenta": "#e24d8e",
    "brightCyan": "#00b39e",
    "brightWhite": "#fcf4dc"
  },
  "tomorrow_night": {
    "name": "Tomorrow Night",
    "background": "#1d1f21",
    "foreground": "#c5c8c6",
    "cursor": "#c5c8c6",
    "selectionBackground": "#373b41",
    "black": "#000000",
    "red": "#cc6666",
    "green": "#b5bd68",
    "yellow": "#f0c674",
    "blue": "#81a2be",
    "magenta": "#b294bb",
    "cyan": "#8abeb7",
    "white": "#ffffff",
    "brightBlack": "#000000",
    "brightRed": "#cc6666",
    "brightGreen": "#b5bd68",
    "brightYellow": "#f0c674",
    "brightBlue": "#81a2be",
    "brightMagenta": "#b294bb",
    "brightCyan": "#8abeb7",
    "brightWhite": "#ffffff"
  },
  "tomorrow_night_bright": {
    "name": "Tomorrow Night Bright",
    "background": "#000000",
    "foreground": "#eaeaea",
    "cursor": "#eaeaea",
    "selectionBackground": "#424242",
    "black": "#000000",
    "red": "#d54e53",
    "green": "#b9ca4a",
    "yellow": "#e7c547",
    "blue": "#7aa6da",
    "magenta": "#c397d8",
    "cyan": "#70c0b1",
    "white": "#ffffff",
    "brightBlack": "#000000",
    "brightRed": "#d54e53",
    "brightGreen": "#b9ca4a",
    "brightYellow": "#e7c547",
    "brightBlue": "#7aa6da",
    "brightMagenta": "#c397d8",
    "brightCyan": "#70c0b1",
    "brightWhite": "#ffffff"
  },
  "tomorrow_night_blue": {
    "name": "Tomorrow Night Blue",
    "background": "#002451",
    "foreground": "#ffffff",
    "cursor": "#ffffff",
    "selectionBackground": "#003f8e",
    "black": "#000000",
    "red": "#ff9da4",
    "green": "#d1f1a9",
    "yellow": "#ffeead",
    "blue": "#bbdaff",
    "magenta": "#ebbbff",
    "cyan": "#99ffff",
    "white": "#ffffff",
    "brightBlack": "#000000",
    "brightRed": "#ff9da4",
    "brightGreen": "#d1f1a9",
    "brightYellow": "#ffeead",
    "brightBlue": "#bbdaff",
    "brightMagenta": "#ebbbff",
    "brightCyan": "#99ffff",
    "brightWhite": "#ffffff"
  },
  "atom": {
    "name": "Atom",
    "background": "#161719",
    "foreground": "#c5c8c6",
    "cursor": "#d0d0d0",
    "selectionBackground": "#444444",
    "black": "#000000",
    "red": "#fd5ff1",
    "green": "#87c38a",
    "yellow": "#ffd7b1",
    "blue": "#85befd",
    "magenta": "#b9b6fc",
    "cyan": "#85befd",
    "white": "#e0e0e0",
    "brightBlack": "#000000",
    "brightRed": "#fd5ff1",
    "brightGreen": "#94fa36",
    "brightYellow": "#f5ffa8",
    "brightBlue": "#96cbfe",
    "brightMagenta": "#b9b6fc",
    "brightCyan": "#85befd",
    "brightWhite": "#e0e0e0"
  },
  "ayu": {
    "name": "ayu",
    "background": "#0f1419",
    "foreground": "#e6e1cf",
    "cursor": "#f29718",
    "selectionBackground": "#253340",
    "black": "#000000",
    "red": "#ff3333",
    "green": "#b8cc52",
    "yellow": "#e7c547",
    "blue": "#36a3d9",
    "magenta": "#f07178",
    "cyan": "#95e6cb",
    "white": "#ffffff",
    "brightBlack": "#323232",
    "brightRed": "#ff6565",
    "brightGreen": "#eafe84",
    "brightYellow": "#fff779",
    "brightBlue": "#68d5ff",
    "brightMagenta": "#ffa3aa",
    "brightCyan": "#c7fffd",
    "brightWhite": "#ffffff"
  },
  "seti": {
    "name": "Seti",
    "background": "#111213",
    "foreground": "#cacecd",
    "cursor": "#e3bf21",
    "selectionBackground": "#303233",
    "black": "#323232",
    "red": "#c22832",
    "green": "#8ec43d",
    "yellow": "#e0c64f",
    "blue": "#43a5d5",
    "magenta": "#8b57b5",
    "cyan": "#8ec43d",
    "white": "#eeeeee",
    "brightBlack": "#323232",
    "brightRed": "#c22832",
    "brightGreen": "#8ec43d",
    "brightYellow": "#e0c64f",
    "brightBlue": "#43a5d5",
    "brightMagenta": "#8b57b5",
    "brightCyan": "#8ec43d",
    "brightWhite": "#ffffff"
  },
  "spacegray": {
    "name": "SpaceGray",
    "background": "#20242d",
    "foreground": "#b3b8c3",
    "cursor": "#b3b8c3",
    "selectionBackground": "#16181e",
    "black": "#000000",
    "red": "#b04b57",
    "green": "#87b379",
    "yellow": "#e5c179",
    "blue": "#7d8fa4",
    "magenta": "#a47996",
    "cyan": "#85a7a5",
    "white": "#b3b8c3",
    "brightBlack": "#000000",
    "brightRed": "#b04b57",
    "brightGreen": "#87b379",
    "brightYellow": "#e5c179",
    "brightBlue": "#7d8fa4",
    "brightMagenta": "#a47996",
    "brightCyan": "#85a7a5",
    "brightWhite": "#ffffff"
  },
  "cobalt2": {
    "name": "Cobalt2",
    "background": "#132738",
    "foreground": "#ffffff",
    "cursor": "#f0cc09",
    "selectionBackground": "#18354f",
    "black": "#000000",
    "red": "#ff0000",
    "green": "#38de21",
    "yellow": "#ffe50a",
    "blue": "#1460d2",
    "magenta": "#ff005d",
    "cyan": "#00bbbb",
    "white": "#bbbbbb",
    "brightBlack": "#555555",
    "brightRed": "#f40e17",
    "brightGreen": "#3bd01d",
    "brightYellow": "#edc809",
    "brightBlue": "#5555ff",
    "brightMagenta": "#ff55ff",
    "brightCyan": "#6ae3fa",
    "brightWhite": "#ffffff"
  },
  "ciapre": {
    "name": "Ciapre",
    "background": "#191c27",
    "foreground": "#aea47a",
    "cursor": "#92805b",
    "selectionBackground": "#172539",
    "black": "#181818",
    "red": "#810009",
    "green": "#48513b",
    "yellow": "#cc8b3f",
    "blue": "#576d8c",
    "magenta": "#724d7c",
    "cyan": "#5c4f4b",
    "white": "#aea47f",
    "brightBlack": "#555555",
    "brightRed": "#ac3835",
    "brightGreen": "#a6a75d",
    "brightYellow": "#dcdf7c",
    "brightBlue": "#3097c6",
    "brightMagenta": "#d33061",
    "brightCyan": "#f3dbb2",
    "brightWhite": "#f4f4f4"
  },
  "afterglow": {
    "name": "Afterglow",
    "background": "#212121",
    "foreground": "#d0d0d0",
    "cursor": "#d0d0d0",
    "selectionBackground": "#303030",
    "black": "#151515",
    "red": "#ac4142",
    "green": "#7e8e50",
    "yellow": "#e5b567",
    "blue": "#6c99bb",
    "magenta": "#9f4e85",
    "cyan": "#7dd6cf",
    "white": "#d0d0d0",
    "brightBlack": "#505050",
    "brightRed": "#ac4142",
    "brightGreen": "#7e8e50",
    "brightYellow": "#e5b567",
    "brightBlue": "#6c99bb",
    "brightMagenta": "#9f4e85",
    "brightCyan": "#7dd6cf",
    "brightWhite": "#f5f5f5"
  },
  "homebrew": {
    "name": "Homebrew",
    "background": "#000000",
    "foreground": "#00ff00",
    "cursor": "#23ff18",
    "selectionBackground": "#083905",
    "black": "#000000",
    "red": "#990000",
    "green": "#00a600",
    "yellow": "#999900",
    "blue": "#0000b2",
    "magenta": "#b200b2",
    "cyan": "#00a6b2",
    "white": "#bfbfbf",
    "brightBlack": "#666666",
    "brightRed": "#e50000",
    "brightGreen": "#00d900",
    "brightYellow": "#e5e500",
    "brightBlue": "#0000ff",
    "brightMagenta": "#e500e5",
    "brightCyan": "#00e5e5",
    "brightWhite": "#e5e5e5"
  },
  "jellybeans": {
    "name": "Jellybeans",
    "background": "#121212",
    "foreground": "#dedede",
    "cursor": "#ffa560",
    "selectionBackground": "#474e91",
    "black": "#929292",
    "red": "#e27373",
    "green": "#94b979",
    "yellow": "#ffba7b",
    "blue": "#97bedc",
    "magenta": "#e1c0fa",
    "cyan": "#00988e",
    "white": "#dedede",
    "brightBlack": "#bdbdbd",
    "brightRed": "#ffa1a1",
    "brightGreen": "#bddeab",
    "brightYellow": "#ffdca0",
    "brightBlue": "#b1d8f6",
    "brightMagenta": "#fbdaff",
    "brightCyan": "#1ab2a8",
    "brightWhite": "#ffffff"
  },
  "jetbrains_darcula": {
    "name": "JetBrains Darcula",
    "background": "#202020",
    "foreground": "#adadad",
    "cursor": "#ffffff",
    "selectionBackground": "#1a3272",
    "black": "#000000",
    "red": "#fa5355",
    "green": "#126e00",
    "yellow": "#c2c300",
    "blue": "#4581eb",
    "magenta": "#fa54ff",
    "cyan": "#33c2c1",
    "white": "#adadad",
    "brightBlack": "#555555",
    "brightRed": "#fb7172",
    "brightGreen": "#67ff4f",
    "brightYellow": "#ffff00",
    "brightBlue": "#6d9df1",
    "brightMagenta": "#fb82ff",
    "brightCyan": "#60d3d1",
    "brightWhite": "#eeeeee"
  },
  "wombat": {
    "name": "Wombat",
    "background": "#171717",
    "foreground": "#dedacf",
    "cursor": "#bbbbbb",
    "selectionBackground": "#453b39",
    "black": "#000000",
    "red": "#ff615a",
    "green": "#b1e969",
    "yellow": "#ebd99c",
    "blue": "#5da9f6",
    "magenta": "#e86aff",
    "cyan": "#82fff7",
    "white": "#dedacf",
    "brightBlack": "#313131",
    "brightRed": "#f58c80",
    "brightGreen": "#ddf88f",
    "brightYellow": "#eee5b2",
    "brightBlue": "#a5c7ff",
    "brightMagenta": "#ddaaff",
    "brightCyan": "#b7fff9",
    "brightWhite": "#ffffff"
  },
  "zenburn": {
    "name": "Zenburn",
    "background": "#3f3f3f",
    "foreground": "#dcdccc",
    "cursor": "#73635a",
    "selectionBackground": "#21322f",
    "black": "#4d4d4d",
    "red": "#705050",
    "green": "#60b48a",
    "yellow": "#f0dfaf",
    "blue": "#506070",
    "magenta": "#dc8cc3",
    "cyan": "#8cd0d3",
    "white": "#dcdccc",
    "brightBlack": "#709080",
    "brightRed": "#dca3a3",
    "brightGreen": "#c3bf9f",
    "brightYellow": "#e0cf9f",
    "brightBlue": "#94bff3",
    "brightMagenta": "#ec93d3",
    "brightCyan": "#93e0e3",
    "brightWhite": "#ffffff"
  },
  "flat": {
    "name": "Flat",
    "background": "#002240",
    "foreground": "#2cc55d",
    "cursor": "#e5be0c",
    "selectionBackground": "#792b9c",
    "black": "#222d3f",
    "red": "#a82320",
    "green": "#32a548",
    "yellow": "#e58d11",
    "blue": "#3167ac",
    "magenta": "#781aa0",
    "cyan": "#2c9370",
    "white": "#b0b6ba",
    "brightBlack": "#212c3c",
    "brightRed": "#d4312e",
    "brightGreen": "#2d9440",
    "brightYellow": "#e5be0c",
    "brightBlue": "#3c7dd2",
    "brightMagenta": "#8230a7",
    "brightCyan": "#35b387",
    "brightWhite": "#e7eced"
  },
  "obsidian": {
    "name": "Obsidian",
    "background": "#283033",
    "foreground": "#cdcdcd",
    "cursor": "#c0cad0",
    "selectionBackground": "#3e4c4f",
    "black": "#000000",
    "red": "#a60001",
    "green": "#00bb00",
    "yellow": "#fecd22",
    "blue": "#3a9bdb",
    "magenta": "#bb00bb",
    "cyan": "#00bbbb",
    "white": "#bbbbbb",
    "brightBlack": "#555555",
    "brightRed": "#ff0003",
    "brightGreen": "#93c863",
    "brightYellow": "#fef874",
    "brightBlue": "#a1d7ff",
    "brightMagenta": "#ff55ff",
    "brightCyan": "#55ffff",
    "brightWhite": "#ffffff"
  },
  "duotone_dark": {
    "name": "Duotone Dark",
    "background": "#1f1d27",
    "foreground": "#b7a1ff",
    "cursor": "#ff9839",
    "selectionBackground": "#353147",
    "black": "#1f1d27",
    "red": "#d9393e",
    "green": "#2dcd73",
    "yellow": "#d9b76e",
    "blue": "#ffc284",
    "magenta": "#de8d40",
    "cyan": "#2488ff",
    "white": "#b7a1ff",
    "brightBlack": "#353147",
    "brightRed": "#d9393e",
    "brightGreen": "#2dcd73",
    "brightYellow": "#d9b76e",
    "brightBlue": "#ffc284",
    "brightMagenta": "#de8d40",
    "brightCyan": "#2488ff",
    "brightWhite": "#eae5ff"
  },
  "glacier": {
    "name": "Glacier",
    "background": "#0c1115",
    "foreground": "#ffffff",
    "cursor": "#6c6c6c",
    "selectionBackground": "#bd2523",
    "black": "#2e343c",
    "red": "#bd0f2f",
    "green": "#35a770",
    "yellow": "#fb9435",
    "blue": "#1f5872",
    "magenta": "#bd2523",
    "cyan": "#778397",
    "white": "#ffffff",
    "brightBlack": "#404a55",
    "brightRed": "#bd0f2f",
    "brightGreen": "#49e998",
    "brightYellow": "#fddf6e",
    "brightBlue": "#2a8bc1",
    "brightMagenta": "#ea4727",
    "brightCyan": "#a0b6d3",
    "brightWhite": "#ffffff"
  },
  "hardcore": {
    "name": "Hardcore",
    "background": "#121212",
    "foreground": "#a0a0a0",
    "cursor": "#bbbbbb",
    "selectionBackground": "#453b39",
    "black": "#1b1d1e",
    "red": "#f92672",
    "green": "#a6e22e",
    "yellow": "#fd971f",
    "blue": "#66d9ef",
    "magenta": "#9e6ffe",
    "cyan": "#5e7175",
    "white": "#ccccc6",
    "brightBlack": "#505354",
    "brightRed": "#ff669d",
    "brightGreen": "#beed5f",
    "brightYellow": "#e6db74",
    "brightBlue": "#66d9ef",
    "brightMagenta": "#9e6ffe",
    "brightCyan": "#a3babf",
    "brightWhite": "#f8f8f2"
  },
  "solarized_light": {
    "name": "Solarized Light",
    "background": "#fcf4dc",
    "foreground": "#536870",
    "cursor": "#536870",
    "selectionBackground": "#eae3cb",
    "black": "#002831",
    "red": "#d11c24",
    "green": "#738a05",
    "yellow": "#a57706",
    "blue": "#2176c7",
    "magenta": "#c61c6f",
    "cyan": "#259286",
    "white": "#eae3cb",
    "brightBlack": "#001e27",
    "brightRed": "#bd3613",
    "brightGreen": "#475b62",
    "brightYellow": "#536870",
    "brightBlue": "#708284",
    "brightMagenta": "#5956ba",
    "brightCyan": "#819090",
    "brightWhite": "#fcf4dc"
  },
  "atomonelight": {
    "name": "AtomOneLight",
    "background": "#f9f9f9",
    "foreground": "#2a2c33",
    "cursor": "#bbbbbb",
    "selectionBackground": "#ededed",
    "black": "#000000",
    "red": "#de3e35",
    "green": "#3f953a",
    "yellow": "#d2b67c",
    "blue": "#2f5af3",
    "magenta": "#950095",
    "cyan": "#3f953a",
    "white": "#bbbbbb",
    "brightBlack": "#000000",
    "brightRed": "#de3e35",
    "brightGreen": "#3f953a",
    "brightYellow": "#d2b67c",
    "brightBlue": "#2f5af3",
    "brightMagenta": "#a00095",
    "brightCyan": "#3f953a",
    "brightWhite": "#ffffff"
  },
  "ayu_light": {
    "name": "ayu_light",
    "background": "#fafafa",
    "foreground": "#5c6773",
    "cursor": "#ff6a00",
    "selectionBackground": "#f0eee4",
    "black": "#000000",
    "red": "#ff3333",
    "green": "#86b300",
    "yellow": "#f29718",
    "blue": "#41a6d9",
    "magenta": "#f07178",
    "cyan": "#4dbf99",
    "white": "#ffffff",
    "brightBlack": "#323232",
    "brightRed": "#ff6565",
    "brightGreen": "#b8e532",
    "brightYellow": "#ffc94a",
    "brightBlue": "#73d8ff",
    "brightMagenta": "#ffa3aa",
    "brightCyan": "#7ff1cb",
    "brightWhite": "#ffffff"
  },
  "github": {
    "name": "Github",
    "background": "#f4f4f4",
    "foreground": "#3e3e3e",
    "cursor": "#3f3f3f",
    "selectionBackground": "#a9c1e2",
    "black": "#3e3e3e",
    "red": "#970b16",
    "green": "#07962a",
    "yellow": "#f8eec7",
    "blue": "#003e8a",
    "magenta": "#e94691",
    "cyan": "#89d1ec",
    "white": "#ffffff",
    "brightBlack": "#666666",
    "brightRed": "#de0000",
    "brightGreen": "#87d5a2",
    "brightYellow": "#f1d007",
    "brightBlue": "#2e6cba",
    "brightMagenta": "#ffa29f",
    "brightCyan": "#1cfafe",
    "brightWhite": "#ffffff"
  },
  "tomorrow": {
    "name": "Tomorrow",
    "background": "#ffffff",
    "foreground": "#4d4d4c",
    "cursor": "#4d4d4c",
    "selectionBackground": "#d6d6d6",
    "black": "#000000",
    "red": "#c82829",
    "green": "#718c00",
    "yellow": "#eab700",
    "blue": "#4271ae",
    "magenta": "#8959a8",
    "cyan": "#3e999f",
    "white": "#ffffff",
    "brightBlack": "#000000",
    "brightRed": "#c82829",
    "brightGreen": "#718c00",
    "brightYellow": "#eab700",
    "brightBlue": "#4271ae",
    "brightMagenta": "#8959a8",
    "brightCyan": "#3e999f",
    "brightWhite": "#ffffff"
  },
  "terminal_basic": {
    "name": "Terminal Basic",
    "background": "#ffffff",
    "foreground": "#000000",
    "cursor": "#7f7f7f",
    "selectionBackground": "#a4c9ff",
    "black": "#000000",
    "red": "#990000",
    "green": "#00a600",
    "yellow": "#999900",
    "blue": "#0000b2",
    "magenta": "#b200b2",
    "cyan": "#00a6b2",
    "white": "#bfbfbf",
    "brightBlack": "#666666",
    "brightRed": "#e50000",
    "brightGreen": "#00d900",
    "brightYellow": "#e5e500",
    "brightBlue": "#0000ff",
    "brightMagenta": "#e500e5",
    "brightCyan": "#00e5e5",
    "brightWhite": "#e5e5e5"
  }
};


function listSchemes() {
  return Object.entries(SCHEMES)
    .map(([id, s]) => ({ id, name: s.name || id }))
    .sort((a, b) => String(a.name).localeCompare(String(b.name), 'en'))
}

function getScheme(id) {
  if (!id) return SCHEMES['pix-dark'] || SCHEMES['dracula'] || Object.values(SCHEMES)[0]
  const raw = String(id)
  if (SCHEMES[raw]) return SCHEMES[raw]
  const key = raw.toLowerCase().replace(/[^a-z0-9]+/g, '_')
  if (SCHEMES[key]) return SCHEMES[key]
  // aliases for removed / renamed ids → nearest working scheme
  const ALIAS = {
    monokai: 'monokai_soda',
    nord: 'spacegray',
    one_dark: 'atom',
    onedark: 'atom',
    solarized: 'solarized_dark',
    solarized_dark_patched: 'solarized_dark',
    espresso: 'afterglow',
    idletoes: 'afterglow',
    batman: 'dracula',
    chalk: 'ciapre',
    chalkboard: 'ciapre',
    dimmedmonokai: 'monokai_soda',
    spacegray_eighties: 'spacegray',
    cobalt_neon: 'cobalt2',
    adventuretime: 'tomorrow_night_blue',
    argonaut: 'dracula',
    ocean: 'cobalt2',
    hybrid: 'atom',
    wez: 'hardcore',
    brogrammer: 'hardcore',
    darkside: 'afterglow',
    firewatch: 'duotone_dark',
    mathias: 'hardcore',
    paulmillr: 'hardcore',
    smyck: 'jellybeans',
    symfonic: 'tomorrow_night_blue',
    twilight: 'zenburn',
    material: 'github',
    clrs: 'terminal_basic',
    novel: 'terminal_basic',
    pencillight: 'atomonelight',
    piatto_light: 'github',
    '3024_day': 'terminal_basic',
    tomorrow_night_eighties: 'tomorrow_night',
    spiderman: 'dracula',
    crayonponyfish: 'dracula',
  }
  // also try hyphen-stripped form of alias keys
  if (ALIAS[key] && SCHEMES[ALIAS[key]]) return SCHEMES[ALIAS[key]]
  return SCHEMES['pix-dark'] || SCHEMES['dracula'] || Object.values(SCHEMES)[0]
}

/** @returns {boolean} whether id is a first-class scheme (not only alias fallback) */
function hasScheme(id) {
  if (!id) return false
  const raw = String(id)
  if (SCHEMES[raw]) return true
  const key = raw.toLowerCase().replace(/[^a-z0-9]+/g, '_')
  return !!SCHEMES[key]
}

function toXtermTheme(scheme) {
  const s = typeof scheme === 'string' ? getScheme(scheme) : scheme || getScheme()
  if (!s) return null
  return {
    background: s.background,
    foreground: s.foreground,
    cursor: s.cursor || s.foreground,
    cursorAccent: s.background,
    selectionBackground: s.selectionBackground || s.brightBlack || '#44475a',
    black: s.black,
    red: s.red,
    green: s.green,
    yellow: s.yellow,
    blue: s.blue,
    magenta: s.magenta,
    cyan: s.cyan,
    white: s.white,
    brightBlack: s.brightBlack,
    brightRed: s.brightRed,
    brightGreen: s.brightGreen,
    brightYellow: s.brightYellow,
    brightBlue: s.brightBlue,
    brightMagenta: s.brightMagenta,
    brightCyan: s.brightCyan,
    brightWhite: s.brightWhite,
  }
}

module.exports = { SCHEMES, listSchemes, getScheme, hasScheme, toXtermTheme }
